name: Waka Readme

on:
  push:
    paths:
      - '.github/workflows/waka-readme.yml'
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: '0 0 * * *' # runs at every 00:00 UTC

jobs:
  update-readme:
    name: Update Wakatime
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          #GH_TOKEN: ${{ secrets.GH_TOKEN }}
          #REPOSITORY: <gh_username/gh_username>
          COMMIT_MESSAGE: "Auto-update"
          BLOCKS: ->  # ⣀⣄⣤⣦⣶⣷⣿, ░▒▓█, ->, etc.
          TIME_RANGE: last_7_days  # last_30_days, last_6_months, last_year, all_time
          SHOW_TITLE: false
          SHOW_TIME: true
          SHOW_TOTAL: false
          SHOW_MASKED_TIME: true  # override SHOW_TOTAL